# Generated by Django 3.0.7 on 2020-06-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
