# Generated by Django 3.0.7 on 2020-06-13 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0002_auto_20200604_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagens',
            options={'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens'},
        ),
    ]
