# Generated by Django 3.0.7 on 2020-06-14 18:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
        ('imagens', '0003_auto_20200613_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagens',
            name='camera',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='cameras.Cameras'),
            preserve_default=False,
        ),
    ]
